### ISSUE TITLE
Headings are not shown on some bibles, GerNeUe in particular [on Mac, v 0.11.0]

### ISSUE THREAD

**Issue by mdbergmann** [tobias-klein/ezra-project#15] opened 2019-12-28 21:12 UTC
See attached screenshots compared to Eloquent on Mac.

<img width="638" alt="Bildschirmfoto 2019-12-28 um 22 10 21" src="https://user-images.githubusercontent.com/2143978/71549513-1e2d5080-29bf-11ea-91aa-01cc546f7de9.png">
<img width="943" alt="Bildschirmfoto 2019-12-28 um 22 10 32" src="https://user-images.githubusercontent.com/2143978/71549514-1e2d5080-29bf-11ea-8f4e-7e98bf185395.png">

**Comment by tobias-klein** [comment] 2019-12-28 22:07
Thanks for this bug report and thanks for looking into Ezra Project on Mac! :)
I have been noticing that behavior with GerNeUe too, but didn't have a closer look yet.
The text is actually returned by the Sword engine like that and as such the root cause is within [node-sword-interface](https://github.com/tobias-klein/node-sword-interface) or Sword itself. For example Genesis 2:4 of GerNeUe comes out like this from the Sword engine.

`<div type="x-milestone" subType="x-preverse" sID="pv1"/><title>Der Anfang der Geschichte </title><div type="x-milestone" subType="x-preverse" eID="pv1"/>Es folgt die Fortsetzung der Geschichte<note annotateRef="Gen.2.4" n="1" osisID="Gen.2.4!note1">Das hebräische toledot bedeutet Weiterentwicklung aus Vorhandenem, es zeigt, wie die Geschichte weitergeht (oder nennt weitere Einzelheiten). Es handelt sich hier also nicht um die Nahtstelle zu einem zweiten Schöpfungsbericht. Toledot wird immer als Überschrift gebraucht, siehe 1. Mose 5,1; 6,9; 10,1; 11,10.27; 25,12.19; 36,1; 37,2.</note> von Himmel und Erde, wie Gott sie geschaffen hat. Als Jahwe<note annotateRef="Gen.2.4" n="2" osisID="Gen.2.4!note2">JHWH. Aus vier Konsonanten besteht der Name Gottes, der besonders die persönliche Nähe zum Menschen ausdrückt. Ausgesprochen wird er wahrscheinlich Jahwe. Siehe das Vorwort des Übersetzers, sowie die Fußnote zu 2. Mose 6,3.</note>, Gott, Himmel und Erde machte,`

The text is simply extracted using `module->getRawEntry()`. After that some filters are applied.
Then `<div type="x-milestone">...</div>` is turned into a section header in Ezra Project.

How are the section headers extracted in Eloquent? I'm guessing that you are using the "entry attrib" mechanism, there? I'm aware of that mechanism, but haven't been using it in Ezra Project yet.

When looking at Gen. 1:1 (GerNeUe) in the raw output of node-sword-interface, there is not even any section header visible in the markup.

**Comment by tobias-klein** [comment] 2019-12-29 16:00
I think I figured it out ... just analyzed the code of other frontends and found out about the X:0 and 0:0 keys for book and chapter introductions/headings.

**Comment by tobias-klein** [comment] 2019-12-30 15:12
I published a beta of a bugfix release that includes the fix:
https://github.com/tobias-klein/ezra-project/releases/tag/0.11.1-beta1

Could you test this once more and confirm whether it looks ok with the new release?
The new release will first migrate the database based on the new version of node-sword-interface. This may take 2-3 minutes.

**Comment by tobias-klein** [comment] 2020-01-04 13:09
@mdbergmann, would you mind confirming that this works now. Then I'll close the issue and publish the bugfix release.

**Comment by mdbergmann** [comment] 2020-01-04 13:34
Yep, I trued to download the binary last week but it took ages.
Will try again and test.
Although, if itworks for you now I don’t see why it shouldn’t work for me.

**Comment by mdbergmann** [comment] 2020-01-05 20:24
OK. It seems to work.
Can be closed.

**Comment by tobias-klein** [comment] 2020-01-05 21:56
Thanks for checking, I appreciate it! Closing this now. The bugfix release will be published tomorrow!

**Closed** 2020-01-05 21:56 UTC
Labels: bug
