### ISSUE TITLE
Stalls at Syncing some Sword Bibles

### ISSUE THREAD

**Issue by mfreeman72** [tobias-klein/ezra-project#12] opened 2019-12-06 21:35 UTC
I just installed Ezra Project version 0.10.0 to see how it compares to other Bible software on Linux. After starting the program, it updates repository data, then attempts to synchronize my Sword Bibles, which I have over 100 of. After several are sync'd just fine, it gets to one and sits there for hours. I'm assuming there's something wrong with the sync, but I'm not sure what. I can close the program, and with some of the stalls, it just goes on from the Bible after that when I restart, but now it's stuck on one and won't go past it after a restart. Is there anything that I can do to get past this problem? It's gotten stuck on at least five Bibles so far, and I've only sync'd 9 of the 111 Bibles I have and I can't seem to go any further. The terminal doesn't report anything at all during the sync process when it gets stuck. I'm running it on Linux Mint 19.2, based on Ubuntu 18.04.

**Comment by tobias-klein** [comment] 2019-12-07 08:00
Thanks for this bug report!
I think I've never tested Ezra Project with such a big amount of local Sword bible modules.
I fear you can't do much right now to get past this. The only chance would be to delete the Ezra Project database (`~/.config/ezra-project/ezra.sqlite`). However, it would probably get stuck again based on the error pattern you're describing above.

If you still want to see Ezra Project in action on your computer, you can also create a separate user (with an empty ~/.sword directory) and then have another look at it using that separate user.

The behavior is certainly a bug. I need to check whether I can reproduce this somehow. First I need to get such an amount of bible translations installed locally. If it's one specific module that it get's stuck at - which one is it? I'm guessing that this could be a bug in the backend ([node-sword-interface](https://github.com/tobias-klein/node-sword-interface)).

The other thing I need to check is whether I can get rid of the database approach for the Sword modules. Currently the content of the Sword modules is transferred into Ezra Project's database when the module is installed (or synced on start-up). This is because Ezra Project used to be a software that only operated based on a database - without Sword.

**Comment by mfreeman72** [comment] 2019-12-07 16:41
I think I have a possible idea for what the problem might be. I cleared the
~/.config/ezra-project folder and started over and paid closer attention to
which modules it got stuck on. There are some Bibles between different
repositories that have different module names, but the same content and
Bible name. (Not sure why I decided to install duplicate Bibles, but there
we are...) These duplicates are the ones it seems to get stuck on. The ones
I've spotted so far are the Douay-Rheims Bible, and ESV. If I delete one of
the duplicates from my Sword sources and start over, Ezra Project continues
fine after that.

As for the database, that makes sense now. I was wondering why it didn't
just use the Sword sources directly. It would certainly make things easier
on the user end, but not sure how fun that job would be for you to remove
the database.

Thanks for the help!

**Comment by tobias-klein** [comment] 2019-12-07 20:32
Regarding the duplicate module names it sounds like something I can watch out for in a condition in the code. Thanks for the additional info! Aside from that: I hope it works fine for you! The database file probably grows rather big with this number of modules ...

**Comment by tobias-klein** [comment] 2019-12-08 14:28
I just tried to reproduce this issue both with the latest code and with 0.10.0, but I couldn't.

1) I created a copy of one module within ~/.sword and gave it the same id => Ezra Project filters it out of the list that is synced on start-up and there is no issue.
2) I created a copy of one module within ~/.sword and gave it a different id but same description => Ezra Project syncs it fine on start-up.

Any additional hints?

**Comment by tobias-klein** [comment] 2020-01-06 11:20
Closing this for now, because it could not be reproduced.

**Closed by tobias-klein** 2020-01-06 11:20 UTC
Labels: bug

**Comment by tobias-klein** [comment] 2020-06-21 08:15
@mfreeman72 
Note that in the latest versions of Ezra Project, the database approach has changed. Bible text is now retrieved directly from SWORD modules during runtime. The database is now only used to store user content. Therefore, all former sync issues should be resolved!
