### ISSUE TITLE
Reports of build problems

### ISSUE THREAD

**Issue by alerque** [tobias-klein/ezra-project#21] opened 2020-02-27 13:40 UTC
I have [a report of problems](https://aur.archlinux.org/packages/ezra-project/#comment-706054) trying to build the Arch Linux package, the user says they had to globally install some NPM module before it would go. Given what I know about this project that should not be the case.

Does that comment mean anything to you? Is there something missing in this projects internal deps? Why would it manifest on some systems and not others?

I'm happy to fix the packaging if there is anything to do, but I don't know what that might be. It's [basically just running](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ezra-project) `electron-rebuild` and `electron-packager` plus adding a wrapper script and desktop file.

**Comment by tobias-klein** [comment] 2020-02-27 19:19
The reports are about the following dependencies:

> Issue fixed after executing these two commands:
> $ sudo npm -g install fstream
> added 16 packages from 4 contributors in 2.429s
> $ sudo npm -g install block-stream
> added 2 packages from 1 contributor in 0.538s
> Then was able to successfully install ezra-project.

I never had to install those packages (fstream, blockstream) explicitly to make Ezra Project successfully build.

The necessary dependencies for building on Linux are documented here:
https://github.com/tobias-klein/ezra-project/blob/master/BUILD.md#install-dependencies

Something currently not in the build instructions (I'll add that) is that electron-packager has to be installed.

**Comment by alerque** [comment] 2020-02-27 21:25
Thanks. I kind of suspect installing those 'deps' only incidentally poked something else on the system, maybe even fixing a broken `npm` or something like that.

In the mean time, what makes you say *electron-packager* has to be installed? I don't have it installed and the build system I'm using works fine because it uses the vendored deps in this project to run `$(npm bin)/electron-rebuild` and such, and apparently you have the electron package specified as a dependency already. It doesn't have to be on the system I don't think.

Also, I looked at the link you sent with this line:

> Install compiler/lib dependencies by running the following command: `sudo apt-get install build-essential npm nodejs libsqlite3-0 libcurl4-gnutls-dev libicu-dev pkg-config git cmake subversion`

Really? Subversion? Are you sure? Cmake?

I understand these are Ubuntu land dependencies and need translating to other distros, but I don't see any part of the build system that uses subversion. Is there some run time dependency on it?

**Comment by alerque** [comment] 2020-02-27 22:03
Wow, I just fell down a rabbit hole and did **not** land in wonderland. I started trying to debuild the build process and there is all sorts of crazy stuff going on. You're mucking around with stuff in node_modules _after_ `npm` does it's thing in there? Ugg. Off with her¹ head!

¹ <sub>"Her" being Electron.</sub>

**Comment by tobias-klein** [comment] 2020-02-28 06:54
> In the mean time, what makes you say _electron-packager_ has to be installed? I don't have it installed and the build system I'm using works fine because it uses the vendored deps in this project to run `$(npm bin)/electron-rebuild` and such, and apparently you have the electron package specified as a dependency already. It doesn't have to be on the system I don't think.

I think you're right about that. electron-packager *is* specified in the dev-dependency list in package.js. I'll take it out of the build page.
> 
> Also, I looked at the link you sent with this line:
> 
> > Install compiler/lib dependencies by running the following command: `sudo apt-get install build-essential npm nodejs libsqlite3-0 libcurl4-gnutls-dev libicu-dev pkg-config git cmake subversion`
> 
> Really? Subversion? Are you sure? Cmake?
> 
> I understand these are Ubuntu land dependencies and need translating to other distros, but I don't see any part of the build system that uses subversion. Is there some run time dependency on it?

node-sword-interface depends on Sword and used to directly fetch the sword sources from the Crosswire SVN repo. As of now, SVN is not needed any longer. For building node-sword-interface Sword is now fetched from the BibleTime Git mirror of the Sword repo. Cmake is also necessary in the context of building Sword.

**Comment by alerque** [comment] 2020-02-28 09:14
> For building node-sword-interface Sword is now fetched from the BibleTime Git mirror of the Sword repo.

Fetched how? Is `git` a build time dependency? Or are you downloading an archive using `curl`? Could this download be injected by the builder instead? Is there a build time option to not download sword at all but link to a system installed one? Should this be an issue on [node-sword-interface](https://github.com/tobias-klein/node-sword-interface)?

> At the time when I integrated this step, node-gyp still depended on Python 2 and used old-style script shebangs [...]

Is this still the case or are those scripts now Python 3 compatible? I only have the system default Python (3.8 right now) document as a dependency, if it also requires Python-2 to build that's something else I should change.

**Comment by tobias-klein** [comment] 2020-02-28 18:21
> Fetched how? Is `git` a build time dependency? Or are you downloading an archive using `curl`? Could this download be injected by the builder instead? Is there a build time option to not download sword at all but link to a system installed one? Should this be an issue on [node-sword-interface](https://github.com/tobias-klein/node-sword-interface)?

Yeah, the actual root-cause is there, but of course it also impacts Ezra Project indirectly.
The script used for building on Linux is this one: [node-sword-interface/scripts/build_sword.sh](https://github.com/tobias-klein/node-sword-interface/blob/master/scripts/build_sword.sh)

The script is linked in [node-sword-interface/binding.gyp](https://github.com/tobias-klein/node-sword-interface/blob/master/binding.gyp).

This script currently uses git and cmake directly.

On your other comment:
> > At the time when I integrated this step, node-gyp still depended on Python 2 and used old-style script shebangs [...]
> 
> Is this still the case or are those scripts now Python 3 compatible? I only have the system default Python (3.8 right now) document as a dependency, if it also requires Python-2 to build that's something else I should change.

The step `npm run cleanup-gyp-shebang` is technically only relevant when generating RPM packages (using electron-installer-redhat) based on a Ezra Project "distribution" (created with electron-packager / `npm run package-linux`). You find a comment in the [actual script](https://github.com/tobias-klein/ezra-project/blob/master/build_scripts/cleanup_gyp_shebang.sh) for this:
> The package node-gyp (Node.js native addon build tool) still depends on Python 2. However, this causes problems with rpm-build.
> The following snippet basically changes all plain Python shebangs of the node-gyp Python scripts to a specific Python 2 shebang

The [corresponding issue on node-gyp](https://github.com/nodejs/node-gyp/issues/1977) is still open.

**Comment by tobias-klein** [comment] 2020-03-02 20:38
@alerque Any additional feedback on this? Since there are no reproducible build issues at the moment I think I'd rather close this issue.

**Closed** 2020-03-03 13:45 UTC

**Comment by alerque** [comment] 2020-03-07 15:39
> The [corresponding issue on node-gyp](https://github.com/nodejs/node-gyp/issues/1977) is still open.

The issue is still open, but reading the comments I have no idea why. It is long since fixed. Also I've been experimenting with builds and am able to get gyp stuff to build just fine with Python 3, including the three packages Ezra depends on.

Your issue here is not that gyp doesn't support Python 3, it's that some distro you are running on only supports Python 2 — or defaults to it or something. I think that hack should be removed from the default build rules and _only_ applied on the specific distro that is a problem.

**Comment by tobias-klein** [comment] 2020-03-08 07:10
> > The [corresponding issue on node-gyp](https://github.com/nodejs/node-gyp/issues/1977) is still open.
> 
> The issue is still open, but reading the comments I have no idea why. It is long since fixed. Also I've been experimenting with builds and am able to get gyp stuff to build just fine with Python 3, including the three packages Ezra depends on.
> 
> Your issue here is not that gyp doesn't support Python 3, it's that some distro you are running on only supports Python 2 — or defaults to it or something. I think that hack should be removed from the default build rules and _only_ applied on the specific distro that is a problem.

Good point! Thanks for paying attention to the quality of the build system here. I'll have another look!

**Comment by tobias-klein** [comment] 2020-03-08 07:33
These are the error messages on CentOS 8 when using rpm tools for packaging:
```
<snip>
*** ERROR: ambiguous python shebang in /usr/lib/ezra-project/resources/app/node_modules/node-gyp/gyp/samples/samples: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/lib/ezra-project/resources/app/node_modules/node-gyp/gyp/gyp_main.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/lib/ezra-project/resources/app/node_modules/node-gyp/gyp/pylib/gyp/easy_xml_test.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
</snip>
```

node-gyp may support Python 3, but as the error messages indicate - it has "ambiguous Python shebangs". And that's what the script cleanup_gyp_shebangs.sh fixes. This looks like it could also become an issue on other (rpm-based) distributions eventually.

**Comment by tobias-klein** [comment] 2020-03-08 08:06
I've now [adjusted](https://github.com/tobias-klein/ezra-project/commit/265ec6ffd16ccfe52a5aa898af68c70865fc9656) the build.sh script, so that it invokes cleanup-gyp-shebang only on rpm-based distributions.
